// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, published_date, language, added_at, added_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateBookParams struct {
	Title         string           `json:"title"`
	Author        string           `json:"author"`
	PublishedDate pgtype.Date      `json:"published_date"`
	Language      string           `json:"language"`
	AddedAt       pgtype.Timestamp `json:"added_at"`
	AddedBy       int32            `json:"added_by"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (int32, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.PublishedDate,
		arg.Language,
		arg.AddedAt,
		arg.AddedBy,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, published_date, language, added_at, added_by, deleted_at, deleted_by
FROM books
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedDate,
		&i.Language,
		&i.AddedAt,
		&i.AddedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAvailableBooks = `-- name: ListAvailableBooks :many
SELECT id, title, author, published_date, language, added_at, added_by
FROM books
WHERE deleted_at IS NULL
`

type ListAvailableBooksRow struct {
	ID            int32            `json:"id"`
	Title         string           `json:"title"`
	Author        string           `json:"author"`
	PublishedDate pgtype.Date      `json:"published_date"`
	Language      string           `json:"language"`
	AddedAt       pgtype.Timestamp `json:"added_at"`
	AddedBy       int32            `json:"added_by"`
}

func (q *Queries) ListAvailableBooks(ctx context.Context) ([]ListAvailableBooksRow, error) {
	rows, err := q.db.Query(ctx, listAvailableBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableBooksRow
	for rows.Next() {
		var i ListAvailableBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.PublishedDate,
			&i.Language,
			&i.AddedAt,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title=$1, author=$2, published_date=$3, language=$4, deleted_at=$5, deleted_by=$6
WHERE id=$7
`

type UpdateBookParams struct {
	Title         string           `json:"title"`
	Author        string           `json:"author"`
	PublishedDate pgtype.Date      `json:"published_date"`
	Language      string           `json:"language"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	DeletedBy     *int32           `json:"deleted_by"`
	ID            int32            `json:"id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.Title,
		arg.Author,
		arg.PublishedDate,
		arg.Language,
		arg.DeletedAt,
		arg.DeletedBy,
		arg.ID,
	)
	return err
}
