// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package generated

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Book struct {
	ID            int32            `json:"id"`
	Title         string           `json:"title"`
	Author        string           `json:"author"`
	PublishedDate pgtype.Date      `json:"published_date"`
	Language      string           `json:"language"`
	AddedAt       pgtype.Timestamp `json:"added_at"`
	AddedBy       int32            `json:"added_by"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	DeletedBy     *int32           `json:"deleted_by"`
	MaxBorrowDays int32            `json:"max_borrow_days"`
}

type BorrowHistory struct {
	ID            int32            `json:"id"`
	BookID        int32            `json:"book_id"`
	UserID        int32            `json:"user_id"`
	BorrowedAt    pgtype.Timestamp `json:"borrowed_at"`
	ReturnedAt    pgtype.Timestamp `json:"returned_at"`
	BorrowedUntil pgtype.Timestamp `json:"borrowed_until"`
}

type Notification struct {
	ID      int32            `json:"id"`
	UserID  int32            `json:"user_id"`
	Message string           `json:"message"`
	SentAt  pgtype.Timestamp `json:"sent_at"`
	Status  string           `json:"status"`
}

type RiverClient struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `json:"river_client_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxWorkers       int64              `json:"max_workers"`
	Metadata         []byte             `json:"metadata"`
	NumJobsCompleted int64              `json:"num_jobs_completed"`
	NumJobsRunning   int64              `json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LeaderID  string             `json:"leader_id"`
	Name      string             `json:"name"`
}

type RiverQueue struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
