// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            int32            `json:"id"`
	Title         string           `json:"title"`
	Author        string           `json:"author"`
	PublishedDate pgtype.Date      `json:"published_date"`
	Language      string           `json:"language"`
	AddedAt       pgtype.Timestamp `json:"added_at"`
	AddedBy       int32            `json:"added_by"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	DeletedBy     *int32           `json:"deleted_by"`
}

type BorrowHistory struct {
	ID         int32            `json:"id"`
	BookID     int32            `json:"book_id"`
	UserID     int32            `json:"user_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	ReturnedAt pgtype.Timestamp `json:"returned_at"`
}

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
