// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, message, sent_at, status)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateNotificationParams struct {
	UserID  int32            `json:"user_id"`
	Message string           `json:"message"`
	SentAt  pgtype.Timestamp `json:"sent_at"`
	Status  string           `json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Message,
		arg.SentAt,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT id, user_id, message, sent_at, status
FROM notifications
WHERE user_id = $1
ORDER BY sent_at DESC
`

func (q *Queries) GetNotificationsByUserID(ctx context.Context, userID int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.SentAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status = $1
WHERE id = $2
`

type UpdateNotificationStatusParams struct {
	Status string `json:"status"`
	ID     int32  `json:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.Status, arg.ID)
	return err
}
